# Configuration for examples runner
# This file allows fine-grained control over example execution

# Examples to always skip
skip:
  - "examples/08_ui/02_interactive_ui_demo.py"  # TUI - requires user interaction

# Custom timeouts for specific examples (in seconds)
timeouts:
  default: 30
  "examples/07_providers/02_gemini_architect.py": 60  # Makes multiple API calls
  "examples/06_integrations/01_pydantic_ai_integration.py": 60  # Complex integration

# API key requirements
# Auto-detected by scanning files, but can be overridden here
requires_api:
  GEMINI_API_KEY:
    - "examples/03_adapters/02_gemini_auto_detect.py"
    - "examples/03_adapters/13_manual_chunk_processing.py"
    - "examples/07_providers/01_gemini_simple_demo.py"
    - "examples/07_providers/02_gemini_architect.py"

  OPENAI_API_KEY:
    - "examples/03_adapters/03_openai_explicit_adapter.py"
    - "examples/06_integrations/01_pydantic_ai_integration.py"

  ANTHROPIC_API_KEY:
    - "examples/03_adapters/04_anthropic_adapter.py"

# Optional package requirements
requires_package:
  ag-ui:
    - "examples/06_integrations/02_agui_integration.py"

# Examples that are expected to be slow (for CI optimization)
slow_examples:
  - "examples/07_providers/02_gemini_architect.py"
  - "examples/06_integrations/01_pydantic_ai_integration.py"

# Categories
# Auto-detected from folder structure, but can be customized
categories:
  00_quickstart:
    - "examples/00_quickstart/*.py"
  01_basics:
    - "examples/01_basics/*.py"
  02_syntaxes:
    - "examples/02_syntaxes/*.py"
  03_adapters:
    - "examples/03_adapters/*.py"
  04_blocks:
    - "examples/04_blocks/*.py"
  05_logging:
    - "examples/05_logging/*.py"
  06_integrations:
    - "examples/06_integrations/*.py"
  07_providers:
    - "examples/07_providers/*.py"
  08_ui:
    - "examples/08_ui/*.py"
  09_advanced:
    - "examples/09_advanced/*.py"
