name: 'Setup Python and uv'
description: 'Setup Python environment with uv package manager'
inputs:
  python-version:
    description: 'Python version to use'
    required: false
    default: '3.13'
  uv-version:
    description: 'uv version to use'
    required: false
    default: 'v5'
  cache-dependency-glob:
    description: 'Glob pattern for cache dependency'
    required: false
    default: 'uv.lock'
  install-dependencies:
    description: 'Whether to install dependencies'
    required: false
    default: 'true'
  dependency-groups:
    description: 'Dependency groups to install (e.g., "dev", "doc", "all")'
    required: false
    default: ''

runs:
  using: "composite"
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        enable-cache: true
        cache-dependency-glob: ${{ inputs.cache-dependency-glob }}

    - name: Set up Python
      shell: bash
      run: uv python install ${{ inputs.python-version }}

    - name: Install dependencies
      if: inputs.install-dependencies == 'true'
      shell: bash
      run: |
        if [ -z "${{ inputs.dependency-groups }}" ]; then
          uv sync
        elif [ "${{ inputs.dependency-groups }}" == "all" ]; then
          uv sync --all-extras --dev
        else
          uv sync --group ${{ inputs.dependency-groups }}
        fi
